url: "https://jaredsburrows.com"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  presentations:
    output: true
    permalink: /:title/

include:
  - '.well-known'

exclude:
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.txt
  - CNAME
