name: build

on:
  push:
    branches:
      - gh-pages
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.6

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Nu HTML Checker
        run: npm install --no-save vnu-jar

      - name: Validate HTML
        run: java -jar node_modules/vnu-jar/build/dist/vnu.jar index.html
